# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 23:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20170712_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tester',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 14, 0, 24, 14, 226835)),
        ),
    ]
